name: starlight_epub_viewer
description: 'Epub viewer for flutter'
version: 0.0.1
homepage: https://github.com/YeMyoAung/starlight_epub_viewer.git
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.8
  path: ^1.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.starlight.starlight_epub_viewer
        pluginClass: EpubViewerPlugin
      ios:
        pluginClass: EpubViewerPlugin